on: 
  schedule:
    - cron: '40 17 * * 0-6'
  push:

jobs:
  job1:
    name: auto push
    runs-on: ubuntu-latest
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        ./config.sh
    - name: bmake
      run: |
        ./bmake.sh
