name: auto push
on:
  push:
    branches: [ "autopush" ]
  workflow_dispatch:
jobs:
  job1:
    name: auto push
    runs-on: ubuntu-20.04
    env:
      password: ${{ secrets.PASS_TEST }}
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        echo $password
        ./config
    - name: bmake
      run: |
        #./bmake
