name: crdroid vendor
on:
  workflow_dispatch:
jobs:
  job1:
    name: auto vendor
    runs-on: ubuntu-20.04
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        ./config
    - name: framework base
      run: |
        #./fwb
