name: auto push
on:
  push:
    branches: [ "autopush" ]
  workflow_dispatch:
jobs:
  job1:
    name: auto push
    runs-on: ubuntu-20.04
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: git config
      run: |
        ./config.sh
    - name: bmake
      run: |
        #./bmake.sh
